# Generated by Django 5.2.17 on 2026-10-01 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programmes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('value', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=200)),
                ('short_name', models.CharField(default='TSCE', max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('phones', models.JSONField(blank=True, default=list)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.CharField(blank=True, max_length=120)),
                ('director_name', models.CharField(blank=True, max_length=120)),
                ('director_title', models.CharField(default='Director, TSCE', max_length=120)),
                ('accepting_applications', models.BooleanField(default=True)),
                ('early_bird_pct', models.PositiveSmallIntegerField(default=15)),
                ('excellence_pct', models.PositiveSmallIntegerField(default=50)),
                ('scholarship_max_pct', models.PositiveSmallIntegerField(default=40)),
                ('excellence_min_waec_year', models.PositiveSmallIntegerField(default=2020)),
                ('excellence_min_as', models.PositiveSmallIntegerField(default=5)),
                ('payment_ref_prefix', models.CharField(default='TSCE-ZP', max_length=20)),
                ('allow_card', models.BooleanField(default=True)),
                ('allow_transfer', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('staff_payment_alerts', models.BooleanField(default=True)),
                ('staff_application_alerts', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='programmes.cohort')),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
