# Generated by Django 5.2.17 on 2026-10-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='scholarship_max_pct',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='application_fee',
            field=models.PositiveIntegerField(default=5000, help_text='Naira, non-refundable, per application'),
        ),
    ]
