# Generated by Django 5.2.17 on 2026-10-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_sitesettings_scholarship_max_pct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='application_fee',
            field=models.PositiveIntegerField(default=5000, help_text='Naira, added to the programme fee (never discounted); paid with it, non-refundable'),
        ),
    ]
