# Generated by Django 5.2.17 on 2026-10-01 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('programme', models.CharField(blank=True, max_length=150)),
                ('subject', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Handled', 'Handled')], db_index=True, default='New', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('audience', models.CharField(choices=[('Public', 'Public'), ('Students', 'Students'), ('Staff', 'Staff')], db_index=True, default='Public', max_length=10)),
                ('tag', models.CharField(blank=True, max_length=40)),
                ('pinned', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], db_index=True, default='Draft', max_length=10)),
                ('author_label', models.CharField(blank=True, help_text='Shown as the sender, e.g. "Admissions Office"', max_length=80)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pinned', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('Academic', 'Academic'), ('Learning', 'Learning'), ('Payments', 'Payments'), ('Certificates', 'Certificates'), ('ICT / Portal', 'Ict'), ('Other', 'Other')], max_length=20)),
                ('priority', models.CharField(choices=[('Normal', 'Normal'), ('High', 'High')], default='Normal', max_length=10)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved')], db_index=True, default='Open', max_length=10)),
                ('reply', models.TextField(blank=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='academics.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('application', 'Application'), ('payment', 'Payment'), ('scholarship', 'Scholarship'), ('result', 'Result'), ('certificate', 'Certificate'), ('announcement', 'Announcement'), ('support', 'Support')], default='announcement', max_length=20)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read'], name='comms_notif_recipie_be4356_idx')],
            },
        ),
    ]
