#!/usr/bin/env bash
# One-time setup of the TSCE portal on an Ubuntu 22.04/24.04 server. Run as root:
#
#   sudo bash bootstrap.sh tsce.com.ng https://github.com/sudaneee/tsce.git [certbot-email|-]
#
# The site answers for DOMAIN and www.DOMAIN. Pass "-" (the default) as the email to
# reuse the server's existing certbot account without registering an email.
#
# Written to be safe on a SHARED server (other sites/apps already running):
#   • only installs missing packages — never upgrades existing ones (no surprise nginx restarts)
#   • adds its own nginx site, never edits or removes other sites; rolls back if `nginx -t` fails
#   • never touches the firewall; uses its own user (tsce), folders and tsce-* systemd units
# Safe to re-run. Afterwards, follow the "Finish" steps it prints.
set -euo pipefail

DOMAIN=${1:?usage: bootstrap.sh DOMAIN REPO_URL CERTBOT_EMAIL}
REPO=${2:?usage: bootstrap.sh DOMAIN REPO_URL CERTBOT_EMAIL}
CERT_EMAIL=${3:--}
APP=/srv/tsce
DATA=/var/lib/tsce
STATIC=/var/www/tsce/static
BACKUPS=/var/backups/tsce
ENV_FILE=$APP/backend/.env

step() { echo; echo "==> $*"; }

step "System packages"
apt-get update -q
DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-upgrade python3 python3-venv python3-pip git nginx sqlite3 \
    certbot python3-certbot-nginx curl

step "Service user and folders"
id tsce >/dev/null 2>&1 || adduser --system --group --no-create-home --home "$APP" --shell /usr/sbin/nologin tsce
usermod -aG tsce www-data                      # nginx reads the gunicorn socket through the tsce group
mkdir -p "$DATA/private_media" "$DATA/media" "$DATA/cache" "$STATIC" "$BACKUPS"
chown -R tsce:tsce "$DATA" "$STATIC" "$BACKUPS"
chmod 750 "$DATA" "$BACKUPS"
chmod 755 "$STATIC"

step "Code ($REPO)"
if [ ! -d "$APP/.git" ]; then
    mkdir -p "$APP" && chown tsce:tsce "$APP"
    # Fetch into the existing folder (it may already hold .ssh with the deploy key,
    # which a plain `git clone` would refuse). A private repo needs that read-only
    # deploy key for the tsce user — see deploy/README.md.
    sudo -u tsce -H git -C "$APP" init -q -b main
    sudo -u tsce -H git -C "$APP" remote add origin "$REPO"
    sudo -u tsce -H git -C "$APP" fetch -q origin main
    sudo -u tsce -H git -C "$APP" checkout -q -t origin/main
else
    echo "already cloned — use deploy/scripts/update.sh to update"
fi
chmod 755 "$APP"

step "Python environment"
[ -d "$APP/backend/.venv" ] || sudo -u tsce python3 -m venv "$APP/backend/.venv"
sudo -u tsce "$APP/backend/.venv/bin/pip" install -q --upgrade pip
sudo -u tsce "$APP/backend/.venv/bin/pip" install -q -r "$APP/backend/requirements.txt"

step "Configuration ($ENV_FILE)"
if [ ! -f "$ENV_FILE" ]; then
    SECRET=$(python3 -c 'import secrets; print(secrets.token_urlsafe(50))')
    cat > "$ENV_FILE" <<EOF
# TSCE production settings — generated by bootstrap.sh on $(date -I). Never commit this file.
DJANGO_SETTINGS_MODULE=config.settings.prod
DJANGO_SECRET_KEY=$SECRET
DJANGO_ALLOWED_HOSTS=$DOMAIN,www.$DOMAIN
DJANGO_CSRF_TRUSTED_ORIGINS=https://$DOMAIN,https://www.$DOMAIN
SITE_URL=https://$DOMAIN
NUM_PROXIES=1

SQLITE_PATH=$DATA/db.sqlite3
PRIVATE_MEDIA_ROOT=$DATA/private_media
MEDIA_ROOT=$DATA/media
CACHE_DIR=$DATA/cache
STATIC_ROOT=$STATIC

# --- Email: Gmail address + App Password (Google Account → Security → App passwords) ---
EMAIL_HOST_USER=
EMAIL_HOST_PASSWORD=
DEFAULT_FROM_EMAIL=

# --- Payments: Zainpay (fill in from the merchant dashboard) ---
PAYMENT_GATEWAY=zainpay
ZAINPAY_ENVIRONMENT=sandbox
ZAINPAY_PUBLIC_KEY=
ZAINPAY_SECRET_KEY=
ZAINPAY_ZAINBOX_CODE=
ZAINPAY_CALLBACK_URL=https://$DOMAIN/api/payments/zainpay/callback
ZAINPAY_PAYER_CHARGE=300
ZAINPAY_CHANNELS=bank_transfer
EOF
    echo "created — fill in the email and Zainpay values before going live"
else
    echo "exists — left unchanged"
fi
chown tsce:tsce "$ENV_FILE"
chmod 600 "$ENV_FILE"

step "Database, static files, school data"
manage() { sudo -u tsce -H bash -c "cd $APP/backend && .venv/bin/python manage.py $*"; }
manage migrate --noinput
manage collectstatic --noinput -v 0
manage seed_school

step "Helper command: tsce-manage"
cat > /usr/local/bin/tsce-manage <<EOF
#!/usr/bin/env bash
# Run a Django management command as the tsce user, e.g.: tsce-manage createsuperuser
exec sudo -u tsce -H bash -c 'cd $APP/backend && .venv/bin/python manage.py "\$@"' tsce-manage "\$@"
EOF
chmod 755 /usr/local/bin/tsce-manage

step "systemd services and timers"
cp "$APP"/deploy/systemd/tsce-*.service "$APP"/deploy/systemd/tsce-*.timer /etc/systemd/system/
chmod 755 "$APP/deploy/scripts/"*.sh
systemctl daemon-reload
systemctl enable --now tsce-gunicorn.service tsce-reconcile.timer tsce-backup.timer
systemctl restart tsce-gunicorn.service

step "nginx (adds the tsce site only)"
if grep -Rls "server_name[^;]*[[:space:]]\(www\.\)\?$DOMAIN[[:space:];]" /etc/nginx/sites-enabled/ /etc/nginx/conf.d/ | grep -v '/tsce$'; then
    echo "!! another nginx site already uses $DOMAIN (listed above) — not touching nginx"; exit 1
fi
if [ ! -f /etc/nginx/sites-available/tsce ]; then   # certbot edits this file later; never overwrite it
    sed "s/__DOMAIN__/$DOMAIN/g" "$APP/deploy/nginx/tsce.conf" > /etc/nginx/sites-available/tsce
fi
ln -sf /etc/nginx/sites-available/tsce /etc/nginx/sites-enabled/tsce
if ! nginx -t; then
    echo "!! nginx config test failed — removing the tsce site so other sites keep working"
    rm -f /etc/nginx/sites-enabled/tsce
    exit 1
fi
systemctl reload nginx

step "HTTPS (Let's Encrypt)"
if [ "$CERT_EMAIL" = "-" ]; then EMAIL_ARGS=(--register-unsafely-without-email); else EMAIL_ARGS=(-m "$CERT_EMAIL"); fi
if certbot certificates 2>/dev/null | grep -q "Domains: $DOMAIN"; then
    echo "certificate already present"
elif certbot --nginx --cert-name "$DOMAIN" -d "$DOMAIN" -d "www.$DOMAIN" --redirect --agree-tos "${EMAIL_ARGS[@]}" --non-interactive \
  || certbot --nginx --cert-name "$DOMAIN" -d "$DOMAIN" --redirect --agree-tos "${EMAIL_ARGS[@]}" --non-interactive; then
    echo "HTTPS enabled"
else
    echo "!! certbot failed — does DNS for $DOMAIN reach this server on port 80?"
    echo "   Re-run later:  certbot --nginx --cert-name $DOMAIN -d $DOMAIN -d www.$DOMAIN --redirect"
fi

cat <<EOF

================================================================================
 Finish (see deploy/README.md):
   1. sudo nano $ENV_FILE        → EMAIL_HOST_USER / EMAIL_HOST_PASSWORD and the ZAINPAY_* keys
   2. sudo systemctl restart tsce-gunicorn
   3. sudo tsce-manage createsuperuser
   4. sudo tsce-manage preflight --send-test-email you@example.com
   5. Zainpay dashboard → webhook URL: https://$DOMAIN/api/payments/zainpay/webhook
   6. Cloudflare → SSL/TLS: use "Full (strict)" now that the origin has a valid certificate
================================================================================
EOF
