# Generated by Django 5.2.17 on 2026-10-01 06:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('start_date', models.DateField()),
                ('enrolment_opens', models.DateField(blank=True, null=True)),
                ('enrolment_closes', models.DateField(blank=True, null=True)),
                ('early_bird_deadline', models.DateField(blank=True, help_text='Early-bird discount applies to payments made before this date.', null=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('track', models.CharField(blank=True, max_length=60)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('weeks', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fee', models.PositiveIntegerField(help_text='Naira')),
                ('capacity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], db_index=True, default='Active', max_length=10)),
                ('icon', models.CharField(default='fa-laptop-code', max_length=40)),
                ('color', models.CharField(default='#1846D6', max_length=9)),
                ('color_bg', models.CharField(default='#EEF3FF', max_length=9)),
                ('overview', models.TextField(blank=True)),
                ('outcomes', models.JSONField(blank=True, default=list)),
                ('audience', models.JSONField(blank=True, default=list)),
                ('careers', models.JSONField(blank=True, default=list)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('schedules', models.JSONField(blank=True, default=list, help_text='Class schedule options offered to applicants')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programmes', to='accounts.staffprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=150)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='programmes.programme')),
            ],
            options={
                'ordering': ['programme', 'order'],
                'constraints': [models.UniqueConstraint(fields=('programme', 'order'), name='unique_module_order')],
            },
        ),
    ]
