# Generated by Django 5.2.17 on 2026-10-01 06:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Late', 'Late'), ('Absent', 'Absent')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('Issued', 'Issued'), ('Revoked', 'Revoked')], default='Issued', max_length=10)),
                ('issued_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.CharField(max_length=80)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Admission Pending', 'Admission Pending'), ('Active', 'Active'), ('Completed', 'Completed'), ('Suspended', 'Suspended'), ('Withdrawn', 'Withdrawn')], db_index=True, default='Admission Pending', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('amount_paid', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('Practical Assignment', 'Practical'), ('Module Test', 'Test'), ('Project', 'Project'), ('Capstone Project', 'Capstone')], max_length=30)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('grade', models.CharField(editable=False, max_length=1)),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], db_index=True, default='Draft', max_length=10)),
                ('assessed_on', models.DateField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['assessed_on'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_no', models.CharField(max_length=30, unique=True, verbose_name='student number')),
                ('first_name', models.CharField(max_length=60)),
                ('middle_name', models.CharField(blank=True, max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('state', models.CharField(blank=True, max_length=40)),
                ('lga', models.CharField(blank=True, max_length=80, verbose_name='LGA')),
                ('qualification', models.CharField(blank=True, max_length=40)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('emergency_contact', models.CharField(blank=True, max_length=200)),
                ('prefs', models.JSONField(blank=True, default=dict, help_text='Notification preferences')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
