# Generated by Django 5.2.17 on 2026-10-01 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('admissions', '0001_initial'),
        ('programmes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='programmes.cohort'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='programmes.module'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='programmes.programme'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='academics.attendancesession'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment', to='admissions.application'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='programmes.cohort'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='programmes.programme'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificate', to='academics.enrollment'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='academics.enrollment'),
        ),
        migrations.AddField(
            model_name='result',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academics.enrollment'),
        ),
        migrations.AddField(
            model_name='result',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='programmes.module'),
        ),
        migrations.AddField(
            model_name='result',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.student'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(fields=('programme', 'cohort', 'date'), name='unique_session_per_day'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('session', 'enrollment'), name='unique_attendance_mark'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.UniqueConstraint(fields=('enrollment', 'module'), name='unique_result_per_module'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'programme', 'cohort'), name='unique_enrollment_per_cohort'),
        ),
    ]
