# Generated by Django 5.2.17 on 2026-10-01 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=20)),
                ('event_type', models.CharField(blank=True, max_length=60)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('headers', models.JSONField(default=dict)),
                ('signature_valid', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('kind', models.CharField(choices=[('charge', 'Charge'), ('refund', 'Refund')], default='charge', max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField(help_text='Naira')),
                ('fee', models.PositiveIntegerField(default=0, help_text='Programme fee before discount')),
                ('discount', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=10)),
                ('channel', models.CharField(blank=True, choices=[('card', 'Card'), ('transfer', 'Bank transfer'), ('virtual', 'Virtual account'), ('other', 'Other')], max_length=10)),
                ('gateway', models.CharField(max_length=20)),
                ('gateway_ref', models.CharField(blank=True, db_index=True, max_length=100)),
                ('checkout_url', models.URLField(blank=True, max_length=500)),
                ('gateway_payload', models.JSONField(blank=True, default=dict, help_text='Last verify/webhook response')),
                ('failure_reason', models.CharField(blank=True, max_length=300)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='admissions.application')),
                ('parent', models.ForeignKey(blank=True, help_text='For refunds: the charge being refunded', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='Set when staff confirm a payment manually', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('kind', 'charge'), ('parent__isnull', True)), models.Q(('kind', 'refund'), ('parent__isnull', False)), _connector='OR'), name='refund_has_parent_charge')],
            },
        ),
    ]
