# Generated by Django 5.2.17 on 2026-10-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('application_fee', 'Application fee'), ('programme_fee', 'Programme fee')], db_index=True, default='programme_fee', max_length=20),
        ),
    ]
