# Generated by Django 5.2.17 on 2026-10-01 06:34

import apps.admissions.models
import apps.core.storage
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programmes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=60)),
                ('middle_name', models.CharField(blank=True, max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10)),
                ('dob', models.DateField(verbose_name='date of birth')),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('address', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=40)),
                ('lga', models.CharField(max_length=80, verbose_name='LGA')),
                ('qualification', models.CharField(max_length=40)),
                ('institution', models.CharField(max_length=200)),
                ('grad_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('waec_status', models.CharField(choices=[('Available', 'Available'), ('Awaiting Result', 'Awaiting'), ('Not Applicable', 'Not Applicable')], max_length=20)),
                ('waec_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('num_as', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9)], verbose_name="number of A's")),
                ('waec_file', models.FileField(blank=True, storage=apps.core.storage.private_storage, upload_to=apps.admissions.models.waec_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('schedule', models.CharField(max_length=80)),
                ('fee', models.PositiveIntegerField()),
                ('discount_type', models.CharField(blank=True, choices=[('earlybird', 'Early Bird Discount'), ('excellence', 'Excellence Award'), ('scholarship', 'Performance Scholarship')], max_length=20)),
                ('discount_pct', models.PositiveSmallIntegerField(default=0)),
                ('discount_amount', models.PositiveIntegerField(default=0)),
                ('amount_payable', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Accepted', 'Accepted'), ('Enrolled', 'Enrolled'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], db_index=True, default='Unpaid', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='programmes.cohort')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='programmes.programme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.CharField(max_length=300)),
                ('ok', models.BooleanField(default=False, help_text='Positive milestone (shown in green)')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='admissions.application')),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AwardRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('excellence', 'Excellence'), ('scholarship', 'Scholarship')], max_length=20)),
                ('requested_pct', models.PositiveSmallIntegerField()),
                ('awarded_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('interview_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('evidence', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=10)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='award_request', to='admissions.application')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
