# Generated by Django 5.2.17 on 2026-10-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awardrequest',
            name='interview_score',
        ),
        migrations.AddField(
            model_name='application',
            name='application_fee',
            field=models.PositiveIntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='application',
            name='application_fee_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('earlybird', 'Early Bird Discount'), ('excellence', 'Excellence Award')], max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text="The applicant's own email (optional for children)", max_length=254),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], db_index=True, default='Unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Awaiting Verification', 'Awaiting Verification'), ('Admitted', 'Admitted'), ('Enrolled', 'Enrolled'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='awardrequest',
            name='type',
            field=models.CharField(choices=[('excellence', 'Excellence')], max_length=20),
        ),
    ]
